resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: glue-viz
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

- template: run-tox-env.yml@OpenAstronomy
  parameters:

    coverage: codecov

    envs:

    - linux: codestyle
      coverage: 'false'

    - linux: py38-test
    - macos: py37-test
    - windows: py36-test

    - linux: py38-notebooks
    - macos: py37-notebooks
    - windows: py36-notebooks
